server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1483
    url: jdbc:postgresql://localhost:5432/scientific_conference
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:file:./db~
#    username: bobur
#    password: 0320
#  sql:
#    init:
#      mode: always

secret:
  key: ApeVFjUOyTmk7XYwgcYwIEsix1mALAsQhftYQqWHE8P6kcnqbZv0Uxj9HduKEvjXzz0sVYCG0ZjSBtmxadtAiQ==

