#mvn spring-boot:run -Dspring.profiles.active=test

##test
#server:
#  port: 8081
#
#spring:
#  datasource:
#    url: jdbc:h2:file:./files
#    driverClassName: org.h2.Driver
#    username: sa
#    password: password
#  sql:
#    init:
#      mode: never
#  h2:
#    console:
#      enabled: true
#      path: /h2-console

server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1483
    url: jdbc:postgresql://localhost:5432/scientific_conference
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

secret:
  key: ApeVFjUOyTmk7XYwgcYwIEsix1mALAsQhftYQqWHE8P6kcnqbZv0Uxj9HduKEvjXzz0sVYCG0ZjSBtmxadtAiQ==
